---
- hosts: ansible
  tasks:
  - name: create docker image
    command: docker build . -t regapp:latest
    args:
     chdir: /opt/docker/
  - name: create tag for docker image
    command: docker tag regapp:latest rajesh1218/regapp:latest
  - name: push the image to docker hub
    command: docker push rajesh1218/regapp:latest
